/*
===========================================================
Customer Lifetime Value Analysis
===========================================================

Business Problem:
The SaaS platform wants to understand which customers, plans, and acquisition sources generate the highest long-term value.

This analysis helps the business:
- identify high-value customers
- compare CLV by acquisition source
- evaluate plan-level revenue performance
- understand whether acquisition cost is justified by revenue
*/

-- Preview revenue records.
SELECT *
FROM clean_revenue
LIMIT 10;


-- 1. Calculate customer lifetime revenue.
-- Customer Lifetime Revenue represents the total revenue generated by each customer across all months.
SELECT customer_id, SUM(amount) AS lifetime_revenue
FROM clean_revenue
GROUP BY customer_id
ORDER BY lifetime_revenue DESC;

-- 2. Calculate customer lifetime value.
-- CLV = total revenue generated by the customer - customer acquisition cost
SELECT c.customer_id, c.plan_type, c.acquisition_cost, 
		SUM(r.amount) AS lifetime_revenue, 
		SUM(r.amount) - c.acquisition_cost AS clv
FROM clean_customers c JOIN clean_revenue r ON c.customer_id = r.customer_id
GROUP BY c.customer_id, c.plan_type, c.acquisition_cost
ORDER BY clv DESC;


-- 3. Analyze average CLV by subscription plan.
WITH customer_clv AS (
    SELECT c.customer_id, c.plan_type, c.acquisition_cost,
        SUM(r.amount) AS lifetime_revenue,
        SUM(r.amount) - c.acquisition_cost AS clv
    FROM clean_customers c
    JOIN clean_revenue r  ON c.customer_id = r.customer_id
    GROUP BY c.customer_id, c.plan_type, c.acquisition_cost
)
SELECT
    plan_type,
    COUNT(DISTINCT customer_id) AS customers,
    ROUND(AVG(lifetime_revenue), 2) AS avg_lifetime_revenue,
    ROUND(AVG(acquisition_cost), 2) AS avg_acquisition_cost,
    ROUND(AVG(clv), 2) AS avg_clv
FROM customer_clv
GROUP BY plan_type
ORDER BY avg_clv DESC;

-- 4. Analyze average CLV by subscription plan.
-- Identifying each customer's acquisition source based on their signup event.
WITH signup_source AS (
    SELECT customer_id, source
    FROM clean_events
    WHERE event_type = 'signup'
),
customer_clv AS (
    SELECT c.customer_id, ss.source, c.plan_type, c.acquisition_cost,
        SUM(r.amount) AS lifetime_revenue,
        SUM(r.amount) - c.acquisition_cost AS clv
    FROM clean_customers c
    JOIN clean_revenue r
        ON c.customer_id = r.customer_id
    LEFT JOIN signup_source ss
        ON c.customer_id = ss.customer_id
    GROUP BY c.customer_id, ss.source, c.plan_type, c.acquisition_cost
)
SELECT
    source,
    COUNT(DISTINCT customer_id) AS customers,
    ROUND(AVG(lifetime_revenue), 2) AS avg_lifetime_revenue,
    ROUND(AVG(acquisition_cost), 2) AS avg_acquisition_cost,
    ROUND(AVG(clv), 2) AS avg_clv
FROM customer_clv
GROUP BY source
ORDER BY avg_clv DESC;

-- 5. Identify the highest-value customers.
WITH customer_clv AS (
    SELECT c.customer_id, c.plan_type, c.acquisition_cost,
        SUM(r.amount) AS lifetime_revenue,
        SUM(r.amount) - c.acquisition_cost AS clv
    FROM clean_customers c
    JOIN clean_revenue r
        ON c.customer_id = r.customer_id
    GROUP BY c.customer_id, c.plan_type, c.acquisition_cost
)
SELECT *
FROM customer_clv
ORDER BY clv DESC
LIMIT 20;